export const GET_CHAT_REQUEST = "GET_CHAT_REQUEST";
export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_FAILED = "GET_CHAT_FAILED";

export const CHAT_REQUEST = "CHAT_REQUEST";
export const CHAT_SUCCESS = "CHAT_SUCCESS";
export const CHAT_FAILED = "CHAT_FAILED";